dist: xenial
language: python
cache: pip

matrix:
  include:
    - env: TOXENV=py36-dj111-wag113
      python: 3.6
    - env: TOXENV=py36-dj111-wag20
      python: 3.6
    - env: TOXENV=py36-dj20-wag20
      python: 3.6
    - env: TOXENV=py36-dj20-wag23
      python: 3.6
    - env: TOXENV=py36-dj20-wag27
      python: 3.6
    - env: TOXENV=py36-dj22-wag27
      python: 3.6
    - env: TOXENV=py37-dj20-wag27
      python: 3.7
    - env: TOXENV=py37-dj22-wag27
      python: 3.7
    - env: TOXENV=flake8
      python: 3.6

install:
  pip install tox

script:
  tox
